"""Schemas package initialization."""

from app.schemas.annotation import (
    AnnotationBase,
    AnnotationCreate,
    AnnotationExport,
    AnnotationFilter,
    AnnotationListResponse,
    AnnotationResponse,
    AnnotationReviewCreate,
    AnnotationReviewResponse,
    AnnotationStats,
    AnnotationSubmit,
    AnnotationSummary,
    AnnotationUpdate,
    AnnotatorInfo,
    BulkAnnotationReview,
    BulkAnnotationReviewResponse,
    TaskInfo,
    VehicleTypeInfo,
)
from app.schemas.pointcloud import (
    BoundingBox,
    FileDownloadResponse,
    FileUploadResponse,
    PointCloudAnalysis,
    PointCloudFileBase,
    PointCloudFileCreate,
    PointCloudFileListResponse,
    PointCloudFileResponse,
    PointCloudFileSummary,
    PointCloudFileUpdate,
    PointCloudPreview,
    PointCloudStats,
)
from app.schemas.project import (
    ProjectBase,
    ProjectCreate,
    ProjectFilter,
    ProjectInvitation,
    ProjectListResponse,
    ProjectMemberBase,
    ProjectMemberCreate,
    ProjectMemberListResponse,
    ProjectMemberResponse,
    ProjectMemberUpdate,
    ProjectPermissions,
    ProjectResponse,
    ProjectStats,
    ProjectSummary,
    ProjectUpdate,
)
from app.schemas.user import (
    EmailVerification,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    TokenData,
    TokenResponse,
    UserBase,
    UserCreate,
    UserLogin,
    UserPublic,
    UserResponse,
    UserStats,
    UserUpdate,
)

__all__ = [
    # Annotation schemas
    "AnnotationBase",
    "AnnotationCreate",
    "AnnotationUpdate",
    "AnnotationSubmit",
    "AnnotationResponse",
    "AnnotationListResponse",
    "AnnotationSummary",
    "AnnotationStats",
    "AnnotationReviewCreate",
    "AnnotationReviewResponse",
    "BulkAnnotationReview",
    "BulkAnnotationReviewResponse",
    "AnnotationFilter",
    "AnnotationExport",
    "AnnotatorInfo",
    "TaskInfo",
    "VehicleTypeInfo",
    # User schemas
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "UserPublic",
    "UserStats",
    "TokenResponse",
    "TokenData",
    "PasswordChange",
    "EmailVerification",
    "PasswordReset",
    "PasswordResetConfirm",
    # Project schemas
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectSummary",
    "ProjectStats",
    "ProjectListResponse",
    "ProjectFilter",
    "ProjectPermissions",
    "ProjectInvitation",
    # Project member schemas
    "ProjectMemberBase",
    "ProjectMemberCreate",
    "ProjectMemberUpdate",
    "ProjectMemberResponse",
    "ProjectMemberListResponse",
    # Point cloud schemas
    "BoundingBox",
    "PointCloudFileBase",
    "PointCloudFileCreate",
    "PointCloudFileUpdate",
    "PointCloudFileResponse",
    "PointCloudFileSummary",
    "PointCloudFileListResponse",
    "FileUploadResponse",
    "FileDownloadResponse",
    "PointCloudAnalysis",
    "PointCloudPreview",
    "PointCloudStats",
]
