"""Schemas package initialization."""

from app.schemas.project import (
    ProjectBase,
    ProjectCreate,
    ProjectFilter,
    ProjectInvitation,
    ProjectListResponse,
    ProjectMemberBase,
    ProjectMemberCreate,
    ProjectMemberListResponse,
    ProjectMemberResponse,
    ProjectMemberUpdate,
    ProjectPermissions,
    ProjectResponse,
    ProjectStats,
    ProjectSummary,
    ProjectUpdate,
)
from app.schemas.user import (
    EmailVerification,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    TokenData,
    TokenResponse,
    UserBase,
    UserCreate,
    UserLogin,
    UserPublic,
    UserResponse,
    UserStats,
    UserUpdate,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "UserPublic",
    "UserStats",
    "TokenResponse",
    "TokenData",
    "PasswordChange",
    "EmailVerification",
    "PasswordReset",
    "PasswordResetConfirm",
    # Project schemas
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectSummary",
    "ProjectStats",
    "ProjectListResponse",
    "ProjectFilter",
    "ProjectPermissions",
    "ProjectInvitation",
    # Project member schemas
    "ProjectMemberBase",
    "ProjectMemberCreate",
    "ProjectMemberUpdate",
    "ProjectMemberResponse",
    "ProjectMemberListResponse",
]
