"""Fix foreign key constraints

Revision ID: 47789f80b9eb
Revises: ac9c1b51c70d
Create Date: 2025-07-05 15:03:09.907886

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47789f80b9eb"
down_revision = "ac9c1b51c70d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "annotation_reviews", "projects", ["project_id"], ["id"]
    )
    op.create_foreign_key(None, "annotations", "projects", ["project_id"], ["id"])
    op.create_foreign_key(None, "pointcloud_files", "projects", ["project_id"], ["id"])
    op.create_foreign_key(
        None, "project_vehicle_types", "projects", ["project_id"], ["id"]
    )
    op.create_foreign_key(None, "tasks", "projects", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "project_vehicle_types", type_="foreignkey")
    op.drop_constraint(None, "pointcloud_files", type_="foreignkey")
    op.drop_constraint(None, "annotations", type_="foreignkey")
    op.drop_constraint(None, "annotation_reviews", type_="foreignkey")
    # ### end Alembic commands ###
